apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer-config
  namespace: kafka
data:
  bootstrap-servers: "kafka-0.broker.kafka.svc.cluster.local:9092,kafka-1.broker.kafka.svc.cluster.local:9092,kafka-2.broker.kafka.svc.cluster.local:9092"
  group_id: "reciever-group1"
  topic: "sendRecieve.t"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-prod-con
  namespace: kafka
  labels:
    component: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kafka-consumer
  template:
    metadata:
      labels:
        component: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: hrishi/kaf-producer-consumer
        env:
        - name: BOOSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-consumer-config
              key: bootstrap-servers
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-consumer-config
              key: group_id
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-consumer-config
              key: topic
---