kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: portworx-sc-secure-sts
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  secure: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: randomizer
  labels:
    component: randomizer
spec:
  clusterIP: None
  selector:
    component: randomizer
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: randomizer
  labels:
    component: randomizer
spec:
  serviceName: randomizer
  replicas: 3
  template:
    metadata:
      labels:
        component: randomizer
    spec:
      containers:
      - name: randomizer
        securityContext:
          privileged: false
        image: hrishi/randomizer:v8
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: portworx-sc-secure-sts # Should match the .metadata.name in the Storageclass spec
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi