apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: kube-system  
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      name: portworx-prometheus-sm
  resources:
    requests:
      memory: 400Mi