---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  namespace: kube-system
data:

  fluent.conf: |
   <source>
     @type systemd
     path /var/log/journal
     filters [{ "_SYSTEMD_UNIT": "docker.service" }]
     pos_file /tmp/dockerservice.pos
     tag journal.dockerd
     read_from_head true
     strip_underscores true
   </source>

    <source>
      @type systemd
      path /var/log/journal
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      pos_file /tmp/k8s-kubelet.pos
      tag journal.kubelet
      read_from_head true
      strip_underscores true
    </source>

    <source>
      type tail
      path /var/log/containers/kube-proxy*.log
      pos_file /tmp/kube-proxy.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%N
      tag kubeproxy.*
      format json
      read_from_head true
      keep_time_key true
    </source>

    <source>
      type tail
      path /var/log/containers/portworx*.log
      pos_file /tmp/px-container.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%N
      tag portworx.*
      format json
      read_from_head true
      keep_time_key true
    </source>

    <filter portworx.**>
      @type rename_key
      rename_rule3 kubernetes.host hostname
    </filter>

    <filter journal.kubelet.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter journal.dockerd.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter **>
      type kubernetes_metadata
    </filter>

    <match>
      @type stdout
    </match>

    <match journal.dockerd.**>
       type elasticsearch_dynamic
       log_level info
       include_tag_key false
       logstash_prefix journal.dockerd.#indexUUID# ## Prefix for creating an Elastic search index.
       host ## Hostname of the ES cluster.
       port 31737
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 60s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>

    <match journal.kubelet.**>
       type elasticsearch_dynamic
       log_level info
       include_tag_key false
       logstash_prefix journal.kubelet.#indexUUID# ## Prefix for creating an Elastic search index.
       host ## Hostname of the ES cluster.
       port 31737
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 60s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>

    <match portworx.**>
       type elasticsearch
       log_level info
       #index_name pxLog.${record['guid']}
       include_tag_key false
       logstash_prefix pxLog.#indexUUID# ## Prefix for creating an Elastic search index.
       host ## Hostname of the ES cluster.
       port 31737
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 60s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>

---
