---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  namespace: kube-system
data:
  fluent.conf: |
   <source>
     @type systemd
     path /var/log/journal
     filters [{ "_SYSTEMD_UNIT": "docker.service" }]
     pos_file /tmp/dockerservice.pos
     tag journal.dockerd
     read_from_head true
     strip_underscores true
   </source>

    <source>
      @type systemd
      path /var/log/journal
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      pos_file /tmp/k8s-kubelet.pos
      tag journal.kubelet
      read_from_head true
      strip_underscores true
    </source>

    <source>
      type tail
      path /var/log/containers/portworx*.log
      pos_file /tmp/px-container.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%N
      tag portworx.*
      format json
      read_from_head true
      keep_time_key true
    </source>

    <filter portworx.**>
      @type rename_key
      rename_rule3 kubernetes.host hostname
    </filter>

    <filter journal.kubelet.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter journal.dockerd.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter **>
      type kubernetes_metadata
    </filter>

    <match journal.dockerd.**>
       type elasticsearch_dynamic
       log_level info
       include_tag_key false
       logstash_prefix #indexUUID#.journal.dockerd ## Prefix for creating an Elastic search index.
       host #ELASTICSEARCH_HOST# ## Hostname of the ES cluster.
       port #ELASTICSEARCH_PORT#
       logstash_format true
       user fluent
       password # Enter the password for the user to connect to ES
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 10s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>

    <match journal.kubelet.**>
       type elasticsearch_dynamic
       log_level info
       include_tag_key false
       logstash_prefix #indexUUID#.journal.kubelet ## Prefix for creating an Elastic search index.
       host #ELASTICSEARCH_HOST# ## Hostname of the ES cluster.
       port #ELASTICSEARCH_PORT#
       logstash_format true
       user fluent
       password # Enter the password for the user to connect to ES
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 10s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>

    <match portworx.**>
       type elasticsearch
       log_level info
       include_tag_key false
       logstash_prefix #indexUUID#.pxLog ## Prefix for creating an Elastic search index.
       host #ELASTICSEARCH_HOST# ## Hostname of the ES cluster.
       port #ELASTICSEARCH_PORT#
       user fluent
       password # Enter the password for the user to connect to ES
       logstash_format true
       buffer_chunk_limit 2M
       buffer_queue_limit 32
       flush_interval 10s  # flushes events ever minute. Can be configured as needed.
       max_retry_wait 30
       disable_retry_limit
       num_threads 8
    </match>
---
