---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
  namespace: kube-system
data:
  fluent.conf: |
   <source>
     @type systemd
     path /var/log/journal
     filters [{ "_SYSTEMD_UNIT": "docker.service" }]
     pos_file /tmp/docker-service.pos
     tag journal.dockerd
     read_from_head true
     strip_underscores true
   </source>

    <source>
      @type systemd
      path /var/log/journal
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      pos_file /tmp/k8s-kubelet.pos
      tag journal.kubelet
      read_from_head true
      strip_underscores true
    </source>

    <source>
      @type systemd
      path /var/log/journal
      filters [{ "_SYSTEMD_UNIT": "portworx.service" }]
      pos_file /tmp/portworxservice.pos
      tag journal.portworx
      read_from_head true
      strip_underscores true
    </source>

    <source>
      type tail
      path /var/log/containers/portworx*.log
      pos_file /tmp/px-container.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%N
      tag portworx.*
      format json
      read_from_head true
      keep_time_key true
    </source>

    <filter portworx.**>
      @type rename_key
      rename_rule3 kubernetes.host hostname
    </filter>

    <filter journal.kubelet.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter journal.dockerd.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter journal.portworx.**>
      @type rename_key
      rename_rule1 MESSAGE log
      rename_rule2 HOSTNAME hostname
    </filter>

    <filter **>
      type kubernetes_metadata
    </filter>
    
    <match journal.portworx.**>
       @type s3
       aws_key_id #AWS_KEY_ID#
       aws_sec_key #AWS_SECRET_KEY_ID#
       s3_bucket #S3_BUCKET#
       s3_region #S3_REGION#
       path logs/
       buffer_path /var/log/journal-portworx/s3
       s3_object_key_format #indexUUID#_%{path}%{time_slice}_%{index}.%{file_extension}          
       time_slice_format %Y%m%d%H
       time_slice_wait 3m
       utc
       buffer_chunk_limit 256m
    </match>

    <match journal.dockerd.**>
       @type s3
       aws_key_id #AWS_KEY_ID#
       aws_sec_key #AWS_SECRET_KEY_ID#
       s3_bucket #S3_BUCKET#
       s3_region #S3_REGION#
       path logs/
       buffer_path /var/log/journal-dockerd/s3
       s3_object_key_format #indexUUID#_%{path}%{time_slice}_%{index}.%{file_extension}          
       time_slice_format %Y%m%d%H
       time_slice_wait 3m
       utc
       buffer_chunk_limit 256m
    </match>

    <match journal.kubelet.**>
       @type s3
       aws_key_id #AWS_KEY_ID#
       aws_sec_key #AWS_SECRET_KEY_ID#
       s3_bucket #S3_BUCKET#
       s3_region #S3_REGION#
       path logs/
       buffer_path /var/log/journal-kubelet/s3
       s3_object_key_format #indexUUID#_%{path}%{time_slice}_%{index}.%{file_extension}          
       time_slice_format %Y%m%d%H
       time_slice_wait 3m
       utc
       buffer_chunk_limit 256m
    </match>

    <match portworx.**>
       @type s3
       aws_key_id #AWS_KEY_ID#
       aws_sec_key #AWS_SECRET_KEY_ID#
       s3_bucket #S3_BUCKET#
       s3_region #S3_REGION#
       path logs/
       buffer_path /var/log/px-container/s3
       s3_object_key_format #indexUUID#_%{path}%{time_slice}_%{index}.%{file_extension}          
       time_slice_format %Y%m%d%H
       time_slice_wait 1m
       utc
       buffer_chunk_limit 256m
    </match>    
---
