apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: kubectl-pod
spec:
  serviceAccountName: tiller
  containers:
  - name: kubectl-pod
    image: "lachlanevenson/k8s-kubectl:v1.8.7"
    args: ['version']